CREATE TABLE TASK (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    BODY TEXT NOT NULL,
    TIME_LIMIT TIMESTAMP WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP WITH TIME ZONE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
